### ISSUE TITLE
[Potential bug] Dimensional Assault does not proc charge effects

### ISSUE THREAD

**Issue by NosVladimir** [alterasc/MicroscopicContentExpansion#10]
Thank you for this wonderful mod!

I was building a cavalier with the idea of using dimensional assault to pair with mounted charge attacks. What I found was that DA can correctly apply the attack bonuses of a charge (including e.g. additional +2 AB provided by Pike Charge from the Disciple of the Pike when using polearms or spears), but it cannot proc additional damage provided by e.g. mythic charge and Fable Hero's Lance. With a normal charge I can proc the additional damage. Would you think the issue is with how DA is implemented, or with how Tabletop-Tweaks changes the charge damage system?

I'm also suspicious towards whether DA can work with Supreme Charge, but was unable to test that as I have not progressed to lv20.

**Comment by alterasc** [comment]
My implementation issue. Will release a fix in a few days (as soon as DLC4 drops).

Thank you for catching this.

**Comment by NosVladimir** [comment]
Thanks for the prompt response! I'm really looking forward to jump scare the enemies

**Comment by alterasc** [comment]
Should be fixed in 1.8.0.
Reopen (or create another issue) if you encounter more bugs.
