### ISSUE TITLE
Dimensional Assault in Turn-Based

### ISSUE THREAD

**Issue by Enkimdu** [alterasc/MicroscopicContentExpansion#11]
I did some testing and dimensional assault does not seem to work in turn based. It does a single attack which does proc death rush and mythic charge but does not proceed with pounce. Works in real time.

Dimensional dervish on the other hand does the full-round attack but without the aforementioned charge bonuses. Also it does this weird thing where pressing space ends the turn while the animation is still running.

**Comment by alterasc** [comment]
Will look at Dimensional Assault.

Dimensional Dervish is not supposed to get charge bonuses, it's not a charge.

The issue with space, I'll look at it too, but that may turn out to be hard.

**Comment by Ardencroft** [comment]
Dimensional Assault also doesnt seem to work with pummeling charge, only giving the first hit, but I suspect its the same bug occurring.

**Comment by alterasc** [comment]
Alright, so here's the result after a bit of fixing and testing

Dimensional Assault works in TBD when you're already in combat. Charge bonuses are applied. If you have pounce it applies.

Dimensional Assault fails to properly initiate combat in TBD.  It just teleports. This bug proved to tricky for me to easily handle, no matter what I did. I'll return to this later.

**Comment by alterasc** [comment]
Should be fixed in 1.13.0
