### ISSUE TITLE
[Error] File 'C:\Program Files (x86)\Steam\steamapps\common\Pathfinder Second Adventure\Mods\MicroscopicContentExpansion\MicroscopicContentExpansion.dll' not found.

### ISSUE THREAD

**Issue by KinnusKitchen** [alterasc/MicroscopicContentExpansion#12]
[MicroscopicContentExpansion] Version '1.8.0'. Loading.
[MicroscopicContentExpansion] Optional mod 'MewsiferConsole.Mod' not found.
[MicroscopicContentExpansion] [Error] File 'C:\Program Files (x86)\Steam\steamapps\common\Pathfinder Second Adventure\Mods\MicroscopicContentExpansion\MicroscopicContentExpansion.dll' not found.
[MicroscopicContentExpansion] Loading time 0.00 s.

Not sure if I did something wrong?

**Comment by alterasc** [comment]
Does this .dll file exists at that path in your PC? Do other mods work for you?

Looks like install problem, I would advise you to get help at mod-user-general channel in owlcat discord.

**Comment by KinnusKitchen** [comment]
It does not exsist. Each time I download it, I do not see it in the file details or .zip package either.

**Comment by alterasc** [comment]
That means you're downloading source code instead of release
https://github.com/alterasc/MicroscopicContentExpansion/releases
