### ISSUE TITLE
Feature Request about Dimensional Dervish feats chain

### ISSUE THREAD

**Issue by Seinra** [alterasc/MicroscopicContentExpansion#13]
Hello, the DarkCodex mod adds a "Blade Rush" infusion/wild talent to the Kineticists... Can you make this infusion work with your "Dimensional Dervish" feats chain? And also add it as one of the possible prerequisites?

**Comment by alterasc** [comment]
Unfortunately not happening.
1. Kineticist stuff is very bothersome to work with.
2. Doesn't work by the rules.

Also I mostly retired from WotR modding, just want to fix couple of remaining bugs and that's it.
