### ISSUE TITLE
Snake Fang does not work with natural attacks (with Feral Combat Training)

### ISSUE THREAD

**Issue by nokturnihs** [alterasc/MicroscopicContentExpansion#18]
Hey there, so doing a monk/natural weapons build with snake fang, claws, bite. Character has feral combat training and (most) other style feat chains work as intended with claws, but it seems that snake fang ONLY works with unarmed strikes, disregarding feral combat training altogether. Is this intended behavior or can we a patch to allow natural weapons to also be used? Thanks in advance!

**Comment by alterasc** [comment]
From my reading of rules it's only unarmed regardless if you have FCT or not. 

In any case FCT is not base game thing, but from another mod and would be very hard to account for.

Sorry if that disappointed you.
