### ISSUE TITLE
Startoss Style does not do a ranged attack

### ISSUE THREAD

**Issue by Brianthas** [alterasc/MicroscopicContentExpansion#19]
I selected startoss style (specifically to do the vital strike feat chain with it) and attempted to use it multiple times, both with and without the vital strike option on. Every time, the character would run up to the enemy and then hit them for 0 damage.

**Comment by alterasc** [comment]
Startoss Style is just a toggle.
Startoss Comet is an active ability. That requires wielding throwing weapon.

Please clarify what you were doing exactly, with which weapon, etc.
If you have a save that doesn't depend on other mods - great. If you can share logs - even greater.

**Comment by alterasc** [comment]
Closing as no additional information was given and everything works for me.
