### ISSUE TITLE
Snake Style Buff

### ISSUE THREAD

**Issue by veidral** [alterasc/MicroscopicContentExpansion#2]
When Snake Style is disabled, the buff above the portrait on the character won't dissapear, and starting Snake Style again gives a new buff icon. Repeating this gives the character a potentially massive amount of buff icons. 

A save and reload seems to fix the issue.

**Comment by alterasc** [comment]
Hi, yes, in some cases (and rarely in base game too in specific circumstances) buff icon can stay after buff removal.  

I'm working on solving it, but this is not a high priority for me right now, since it's just an UI issue.

**Comment by alterasc** [comment]
Fixed in 1.4.1
