### ISSUE TITLE
Tyrant and Smite

### ISSUE THREAD

**Issue by RevanStarforge** [alterasc/MicroscopicContentExpansion#3]
Tyrant (the lawful evil variant) variant of the Antipaladin suppose to have Smite Chaos instead of Smite Good, at least it looks that way in the table... is this intentional.. or just a ui error i don't know, but i wanted to ask/point out

**Comment by alterasc** [comment]
Tyrant having Smite Chaos was Call of the Wild homebrew.

Visit https://www.d20pfsrd.com/classes/alternate-classes/antipaladin/archetypes/paizo-antipaladin-archetypes/tyrant-antipaladin-archetype/ to see that Tyrant archetype does not change Smite Good.
