### ISSUE TITLE
Selecting character in battle bug

### ISSUE THREAD

**Issue by Xyrmes** [alterasc/MicroscopicContentExpansion#4]
I'm not sure what causes it, but some time in act 2, the classes being modded in, such as antipaladin, become unselectable with healing and buff spells during combat, at least in turn-based mode. This applies to abilities others use, as well as their own abilities, if they require mousing over them or their portrait to use it.

It also seems that any class outfits they have vanish, leaving them naked underneath whatever armor they have on.

**Comment by alterasc** [comment]
What mods you use?
Do you gestalt?

> the classes being modded in, such as antipaladin

So it happens for classes added by other mods too? Or you only checked that it happens for antipaladin in your game?

**Comment by Xyrmes** [comment]
So far, antipaladin from this and brawler from _Brawler Class_, which hasn't been updated in a while. I haven't tested every single modded class I have, but it doesn't seem to affect modded archetypes for existing classes. I'm not using any gestalt classes.

The mods I'm using:
Enforcer Archetype: https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/286
Asmodean Enforcer Archetype: https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/284
Scaling Cantrips: https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/64
Companion Respec: https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/309
Toy Box: https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/8
Bubble Buff Bot: https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/195
Alternate Human Traits: https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/337
Brawler Class: https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/207
Spars Sundries: https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/339
Homebrew Archetypes: https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/279
Kineticist Expanded Elements: https://github.com/SpencerMycek/KineticistExpandedElements
Tome of the Firebird: https://github.com/pheonix99/TomeOfTheFirebird
And the Tabletop Tweaks mods: https://github.com/Vek17/TabletopTweaks-Core, https://github.com/Vek17/TabletopTweaks-Base, https://github.com/Vek17/TabletopTweaks-Reworks

**Comment by alterasc** [comment]
Thank you for the details.  
If it happens to me I'll look at it.

**Comment by Xyrmes** [comment]
> Thank you for the details. If it happens to me I'll look at it.

I think I found the issue, and it wasn't with your mod. _Spars Sundries_ had some bug that made modded classes become naked and unselectable, at least with some accessories. Removing that mod got rid of it, it seems.
