### ISSUE TITLE
Prestige classes can't progress Antipaladin casting

### ISSUE THREAD

**Issue by 666lumberjack** [alterasc/MicroscopicContentExpansion#6]
Tested with Mystic Theurge, Loremaster and Hellknight Signifier. They do recognise you as a divine spellcaster when considering whether you qualify for them, but don't allows you to select Antipaladin as the spellbook to progress.

**Comment by alterasc** [comment]
Will try to fix in next release.

**Comment by alterasc** [comment]
Fixed in 1.5.0
