### ISSUE TITLE
Snake Fang Issue

### ISSUE THREAD

**Issue by DanZinagri** [alterasc/MicroscopicContentExpansion#7]
Unless i'm missing something it doesn't seem to be working.

I'll admit i got a weird build, so i tried it in different configurations.
1. Using a shield + punching dagger - i wanted to see if it would do it, didn't think it would, but thought i'd see if it would bascailly try to do kicks in retalliation; i doubt this is a bug, more just how the base game handles unarmed strikes.
2. Using a shield + unarmed strike - i expected this to work; i know the game won't do TWF with the shield when you are just punching with the main hand (hence the above method); but let the enemy miss me for about 3 rounds, no op attacks were made.
3. No shield, only unarmed - no dice on this one either.

I'm just using this + Vek17s other mods (Core/Tweaks/Reworks/Archetypes/FocusPlus). My character is 1 level rogue + 10 levels fighter, using a background to get unarmed strike.

I have two-weapon fighting, shield bash, wearing heavy armor. So unless i'm maybe missing something here, it should work; as i don't see any listed restrictions on the feat.

**Comment by alterasc** [comment]
Just tested on game version 2.0.3i, TTT-Core 0.5.4 and MicroscopicContentExpansion 1.5.0 and configuration 3 worked for me.

Do you have Snake Style toggled on?

**Comment by DanZinagri** [comment]
I was on TTT-Core 0.5.3 as i didn't see the update that wasn't that long ago. But otherwise everything else is the same; Snake style is on, and i can see the value in my AC calculation column. I just updated to the same version; While some of these misses are from blur, so i assume it only tracks from actual AC misses, not concealment misses; at least 3 of these are from actual attack roll misses, in melee.
![image](https://user-images.githubusercontent.com/98767002/200027092-970b4625-4a6a-4fa6-882d-b425e957bb55.png)

I tried with the shield bash feat toggled on and off as well.

**Comment by DanZinagri** [comment]
Unfortunately, because this character is a heavy armor build doing this; I don't know if this feat has some secret armor-related restriction in the background, as most characters who likely would take this are monks (being the most likely to do unarmed builds); as obviously if i took off my armor i'd suffer such a significant loss to AC i wouldn't be able to properly test.

I'll fully admit this is a very oddball build i'm doing here; primarily to see what i could do here; but i would think the basic premise of "attack misses me i make AoO" should still function.

I did a test after the above screenshot again re-toggling on/off the feat and taking off the shield to be fully unarmed (as i noticed i was still bashing with the shield despite the feat for bashing being toggled off); but neither worked.

**Comment by DanZinagri** [comment]
For further proof i should have everything in order: 
![image](https://user-images.githubusercontent.com/98767002/200029379-c50ca13c-c570-46bc-877a-39f5abf17c2e.png)

**Comment by alterasc** [comment]
There's no checks for armor.  
It checks for 
- attack not being a hit
- you having snake style buff and taken snake fang
- first weapon being unarmed strike.

So armor does not have any impact at all. Enabled shield bash - maybe can matter. But you said you tried with shield taken off entirely.
I tested with armor on and with shield in off-hand too. Still works on my side.

Maybe you have something overriding your unarmed strike? Claws from some source?

You could try sending me save file to alterasc **at** protonmail.com and I'll try looking at it next week.

**Comment by DanZinagri** [comment]
Just sent it off; i would love if it was something really simple that I'm missing. I even wondered if there was something AoO related, but the character seems to be able to make those normally; I have Combat reflexes, +5 dex mod. and the ever-ready so i should have 7 AoO to work with here. Character seems to be able to do normal AoO (parking them next to a bow user, someone tries to run past them, etc..),

I had tested pre-getting the steel headbutt ability from fighter also (1 level later), so i don't think thats the problem; and that only functions during full attacks.

Character is full human with no natural weapons; and i'm using greater magic fang to buff the unarmed strike when using that. Even better this character isn't even utilizing the achetype-stacking from Vek17s other mod; its 1 level Sylvan Trickster rogue, and the rest is straight no-archetype fighter.

So at least from my end , i'm completely stumped what i could be doing wrong here.

**Comment by alterasc** [comment]
Thanks for save file.
Problem was in checking for unarmed strike for non-monks.

Reworked code a bit, tried on your save, now (in 1.5.1) it's working.

Won't work with punching dagger, but unarmed strike + enabled shield bash qualifies.

**Comment by DanZinagri** [comment]
Finished that other save yesterday for that DLC so i had to quick cheaty my way into a new character to test that with, but looks to be working now. I had wondered if it was a monk thing, but wasn't certain as i don't know how this game handles the difference between monks and non-monks on that.

Thanks for the assistance on this!
