### ISSUE TITLE
Startoss Comet and special ammunition quivers

### ISSUE THREAD

**Issue by AnonymousPepper** [alterasc/MicroscopicContentExpansion#8]
So, I'm all for being able to use Cold Iron Quivers and the like with thrown weapons, that's a vanilla game feature and all, but using Startoss Comet appears to consume ammunition from them per attack. This doesn't strike me as correct, as Startoss Style is one projectile bouncing between targets.

Is this possible to fix?

**Comment by alterasc** [comment]
Possible, but hacky, so highly likely I'm not touching it.

I'll leave this issue open for some time until I make a final decision.

**Comment by alterasc** [comment]
Did a bit more digging. 

I'm leaving this as is.
